server:
  port: 8083
spring:
  application:
    name: store-service
  thymeleaf:
    suffix: .html
    prefix: classpath:/templates/
    cache: false


  datasource:
    url: jdbc:mysql://localhost:3306/rsv?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: reservation
    password: 1

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      port: 6379
      host: localhost
      password: ""
  mvc:
    hidden method:
      filter:
        enabled: true # hidden 타입의 input 태그 속성을 필터링해주어 각 요청의 HTTP 메서드를 읽어서 변경해준다.
logging:
  level:
    org.springframework.security: debug
# swagger
springdoc:
  #  packages-to-scan: com.project.reservation-service
  cache:
    disabled: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  swagger-ui:
    # Swagger UI 사용여부 : 접근 경로 => <http://localhost:8082/swagger-ui/index.html>
    enabled: true
    path: /test-ui.html
    # path: /demo-ui.html # Swagger UI 추가 접근 경로 => <http://localhost:8080/test-ui.html>
    tags-sorter: alpha
    # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha
